[package]
name = "move-coverage"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra Move VM code coverage"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
once_cell = "1.4.1"
structopt = "0.3.18"
serde = { version = "1.0.116", default-features = false }
anyhow = "1.0.33"
codespan = { version = "0.8.0", features = ["serialization"] }
colored = "2.0.0"

bcs = { path = "../../../common/bcs", version = "0.1.0", package = "diem-canonical-serialization" }
diem-types = { path = "../../../types", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
move-ir-types = { path = "../../move-ir/types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
vm = { path = "../../vm", version = "0.1.0" }
bytecode-source-map = { path = "../../compiler/bytecode-source-map", version = "0.1.0" }

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
