[package]
name = "errmapgen"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
publish = false
edition = "2018"
license = "Apache-2.0"

[dependencies]
# diem dependencies
spec-lang = { path = "../spec-lang", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
diem-types = { path = "../../../types", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
bcs = { path = "../../../common/bcs", version = "0.1.0", package = "diem-canonical-serialization" }

# external dependencies
log = "0.4.11"
anyhow = "1.0.33"
serde = { version = "1.0.116", features = ["derive"] }

[dev-dependencies]
codespan-reporting = "0.8.0"
move-prover = { path = "..", version = "0.1.0" }
datatest-stable = { path = "../../../common/datatest-stable", version = "0.1.0" }
test-utils = { path = "../test-utils", version = "0.1.0" }
