[package]
name = "diem-secure-storage"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.org>"]
repository = "https://github.com/diem/diem"
description = "Diem's Persistent, Secure Storage"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
enum_dispatch = "0.3.3"
rand = "0.7.3"
serde = { version = "1.0.116", features = ["rc"], default-features = false }
serde_json = "1.0.58"
thiserror = "1.0.21"

consensus-types = { path = "../../consensus/consensus-types", version = "0.1.0" }
bcs = { path = "../../common/bcs", version = "0.1.0", package = "diem-canonical-serialization" }
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
diem-github-client = { path = "github", version = "0.1.0" }
diem-global-constants = { path = "../../config/global-constants", version = "0.1.0"}
diem-infallible = { path = "../../common/infallible", version = "0.1.0" }
diem-logger = { path = "../../common/logger", version = "0.1.0" }
diem-secure-time = { path = "../time", version = "0.1.0" }
diem-temppath = { path = "../../common/temppath", version = "0.1.0" }
diem-types = { path = "../../types", version = "0.1.0" }
diem-vault-client = { path = "vault", version = "0.1.0" }
diem-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }

[dev-dependencies]
diem-crypto = { path = "../../crypto/crypto", version = "0.1.0", features = ["fuzzing"] }
diem-crypto-derive = { path = "../../crypto/crypto-derive", version = "0.1.0" }
rand = "0.7.3"

[features]
fuzzing = ["diem-crypto/fuzzing"]
testing = []
