[package]
name = "bytecode-source-map"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.33"
diem-types = { path = "../../../types", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
move-ir-types = { path = "../../move-ir/types", version = "0.1.0" }
vm = { path = "../../vm", version = "0.1.0" }
bcs = { path = "../../../common/bcs", version = "0.1.0", package = "diem-canonical-serialization" }
codespan = "0.8.0"
codespan-reporting = "0.8.0"
serde = { version = "1.0.116", default-features = false }

[features]
default = []
fuzzing = ["diem-types/fuzzing"]
