[package]
name = "move-explain"
version = "0.1.0"
authors = ["Libra Association <opensource@diem.org>"]
description = "Libra Move abort code explanations"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
structopt = "0.3.18"
compiled-stdlib = { path = "../../stdlib/compiled", version = "0.1.0" }
diem-workspace-hack = { path = "../../../common/workspace-hack", version = "0.1.0" }
errmapgen = { path = "../../move-prover/errmapgen", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
bcs = { path = "../../../common/bcs", version = "0.1.0", package = "diem-canonical-serialization" }

[features]
default = []
